version: 0.1
os: linux
files:
  - source: /
    destination: /home/ec2-user/build/
hooks:
  BeforeInstall:
    - location: scripts/beforeinstall.sh
      timeout: 300
  AfterInstall:
    - location: scripts/afterinstall.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/applicationstart.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/applicationstop.sh
      timeout: 300