version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/build/

# permissions:
#   - object: /
#     owner: ec2-user
#     group: ec2-user
#     mode: 755
hooks:
  BeforeInstall:
      - location: scripts/beforeinstall.sh
        timeout: 300
        runas: root
  AfterInstall:
    - location: scripts/afterinstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/applicationstart.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/applicationstop.sh
      timeout: 300
      runas: root