name: CI CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  LIGHTSAIL_SSH_KEY: ${{ secrets.LIGHTSAIL_SSH_KEY }}
  LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
  LIGHTSAIL_USERNAME: ec2-user
  AWS_REGION: ap-northeast-2

jobs:
  build:
    runs-on : ubuntu-latest
    steps:
      - name: 해당 브런치로 체크아웃
        uses: actions/checkout@v2
  
      # nodeJs를 설치합니다.
      - name: 노드 설치
        uses: actions/setup-node@v4.0.0

      # package.json의 dependencies 설치
      - name: 프로젝트 디펜던시 설치
        run: yarn

      # 프로젝트를 빌드합니다.
      - name: 프로젝트 빌드하기
        run: yarn build

      # 빌드 파일이 생성되었는지 확인합니다.
      - name: 빌드 파일 생성 체크
        run: ls -la
