name: CI CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  LIGHTSAIL_SSH_KEY: ${{ secrets.LIGHTSAIL_SSH_KEY }}
  LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
  LIGHTSAIL_USERNAME: ec2-user
  AWS_REGION: ap-northeast-2

jobs:
  build:
    runs-on : ubuntu-latest
    steps:
      - name: 해당 브런치로 체크아웃
        uses: actions/checkout@v2
  
      # nodeJs를 설치합니다.
      - name: 노드 설치
        uses: actions/setup-node@v1
